server:
  port: ${SERVER_PORT}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:development}

freeswitch:
  user-directory-path: ${FS_USER_DIRECTORY_PATH}
  host: ${FS_HOST}
  port: ${FS_HTTP_PORT}
  webapi: ${FS_WEB_API_URL}
