# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Publish Java JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest

    steps:
      - name: Sync repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Release
        run: |
          currentVersion=$(cat pom.xml | sed -e ':a;N;$!ba;s:\n::g;s: *::g;s:.*<version>\(.*\)-SNAPSHOT<\/version>.*:\1:g')
          echo "--- Releasing: $currentVersion ---"
          sed -i "s:$currentVersion-SNAPSHOT:$currentVersion:g" pom.xml
          mvn deploy -s $GITHUB_WORKSPACE/settings.xml -DskipTests
          echo "currentVersion=$currentVersion" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Bump version
        run: |
          currentVerArr=($(echo $currentVersion | tr '.' '\n'))
          currentVerArr[2]=$((currentVerArr[2] + 1))
          IFS=. eval 'nextSnapshotVersion="${currentVerArr[*]}"'
          echo "--- Bump to $nextSnapshotVersion-SNAPSHOT ---"
          sed -i "s:$currentVersion:$nextSnapshotVersion-SNAPSHOT:g" pom.xml

      - name: Git push
        run: |
          git config user.email "eldar.jah@gmail.com"
          git config user.name "Git Workflow"
          echo "--- Pushing to `main` ---"
          git diff
          git add pom.xml
          git commit -m "Git Workflow Auto Versioning"
          git push origin main
          echo "--- Successfully pushed to `main` ---"
        env:
          GITHUB_TOKEN: ${{ github.token }}
